### ISSUE TITLE
It fill's up to 100% when relog!

### ISSUE THREAD

**Issue by ChrisGaming** [GamerKing195/Thirst#4]
When I relog to the game the thirst get's up to 100% and it's really bad in survival!

**Comment by cadenkriese** [comment]
What version are you using? Also please provide console if there are any errors.

**Comment by cadenkriese** [comment]
Also please define, "really bad in survival".

**Comment by ChrisGaming** [comment]
Thanks for replying! I use Craftbukkit 1.10. So it's really bad in survival because when players thirst get down to 1-2% they just relog and get's up to 100%. And also when I type /thirst it shows an error like in the 1. picture.
![error](https://cloud.githubusercontent.com/assets/23278498/20036978/e933ed38-a417-11e6-894d-77227dddd5f2.png)
![error2](https://cloud.githubusercontent.com/assets/23278498/20036979/e937cf7a-a417-11e6-9c9f-77c02e031dd6.png)

**Comment by cadenkriese** [comment]
Hello,
Please send me your plugins list, your thirst config, and the version of Thirst that you are using.
Regards,
      GamerKing195

**Comment by ChrisGaming** [comment]
Here is the plugins: AuthMe, BossShop, ChestCommands, Citizens, ColoredAnvils, CommandNPC, CustomJoinItems, CustomRecipes, CS-CoreLib, DJ, Echopet, Elytra, EssentialsX, EssentialsXChat, EssentialsXSpawn, HolographicsDisplays, Multivese-Core, MythicLib, MythicMobs, NoteBlockAPI, PermissionEX, PerWorldPlugin, Pixelator, PlayerParticles, ProtocolLIB, RandomTP, ServerMusic, SkinRestorer, SuperTrails, SuperVanish, TabAPI, Thirst, Tim, Vault, WorldEdit, WorldGuard.
I'm using version: Thirst 1.5.1.

[config.zip](https://github.com/GamerKing195/Thirst/files/574021/config.zip)

**Comment by cadenkriese** [comment]
Sorry for the late response, I can't seem to replicate the bug you are having. The only thing that would reset a players thirst when they relog is something happening to the thirst_data.yml file on your server. Also, make sure that you are using Spigot while running this, as support for someone using Bukkit will not be given.

If you want, you can download the jar for the latest version of spigot [Here](https://www.dropbox.com/s/097altpxsbj30mo/spigot-1.10.2.jar?dl=0). However, support will not be given by the official Spigot team, if errors occur whilst using it, due to it being compiled by me.

If you start using that jar and the errors continue, please contact me via Skype (gamerking195) and I will attempt to help you solve the error.

```
       Regards,
           ~ GamerKing195
```

**Comment by ChrisGaming** [comment]
Hi! Thanks for the advide! We put our server to spigot and it works perfectly, thanks! Also I wondering that is could be possible to make it per world this plugin because perworldplugin can not do it.
Thanks!

**Comment by cadenkriese** [comment]
Hello,

It's fairly difficult for me to understand what you were trying to say when you said "Also I wondering that is could be possible to make it per world this plugin because perworldplugin can not do it." if you are asking me to add a feature where thirst only operates in certain worlds, it is already added since version 1.5.1. There is a config option near the bottom In disabled areas called disabled worlds where you can disable thirst for a certain world.

Example: 

DisabledWorlds:
     - World1
     - World2

If you had worlds 1, 2, and 3 then with that thirst would only be enabled in World3. Also please don't respond to this issue anymore as it is closed if you want more support you can either post in the discussion (https://www.spigotmc.org/threads/thirst.154422/), or contact me on Skype (gamerking195).

```
 Hope this helps,
      ~ GamerKing195
```

**Comment by ChrisGaming** [comment]
Thank you a lot!
