### ISSUE TITLE
"A severe error has occured with the Thirst plugin"

### ISSUE THREAD

**Issue by MrAniman2** [GamerKing195/Thirst#7]
I have been using this plugin for already few days without any issues but now suddenly it gives this error on player join/leave.

https://pastebin.com/pYhheGeX

Thank you.

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Auto-Updater connection refused bug.](https://trello.com/c/DTUlx9nC/24-fix-auto-updater-connection-refused-bug)

**Comment by cadenkriese** [comment]
Hey there, thank you for reporting this bug, does this only happen when players that have the permission thirst.command.update or are opped join/leave or everyone? Also, has the auto-updater from version 1.7.1 » 1.7.2 worked or have you not tested?

The error occurs because your server is trying to ping a service that is refusing the connection or "shutting it out" I'll look into a fix but the plugins main mechanics should be fine, however, the auto-updater on this version will probably not work.

I will respond to this thread once the bug has been fixed (and the update has been published) however you can monitor my progress on it [here](https://trello.com/c/DTUlx9nC/24-fix-auto-updater-connection-refused-bug).

**Comment by MrAniman2** [comment]
Thank you for reply, I just installed plugin again and got the same error on first join (as op) after restart but after that I couldn't replicate the error anymore...not with/without op or permission you provided (did few restarts as well) Now plugin seems to be working completely fine :/

No I haven't tried auto updater.

**Comment by cadenkriese** [comment]
Yeah, Thirst is trying to ping the spigot website to check for updates on login but I'm going to change it to where it checks on startup and saves the data to be more optimized. 

Also since I'm pinging spigot so much I think it just refused the connection from your servers IP, then after a period of time, it started allowing requests again. I'll try and get the update out later tonight so until then try not to log in too frequently if you are op or have the permission. thirst.command.update.

Again, sorry for the inconvenience,
        ~ Gamer

**Comment by cadenkriese** [comment]
This bug has been fixed in Thirst V1.7.3, you can manually download the update [here](https://www.spigotmc.org/resources/thirst.24610/). Or test out the updater and have it update for you (/thirst update).
