### ISSUE TITLE
Metadatas

### ISSUE THREAD

**Issue by The-Mr-Mango** [GamerKing195/Thirst#9]
Hello GamerKing,

first of all: youre a king! this plugin rocks.
yet, i have some issues with the metadatas. the potion metadatas wont work (and the fact that you have to place the metadatas after the item id is a bit annoying aswell) i tried making thick potions, awkward potions and regular water bottles have a different replenish amount, but it did not work :(
can you fix this, or explain to me how to fix this myself (im not sure if i am doing something wrong)
and could you please think of a different way to store this info
maybe by doing:

item id: metadata = replenish amount

so for example:

373:1 = 50

**Comment by cadenkriese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FIX - Item metadatas not working.](https://trello.com/c/tp2OeAk5/43-fix-item-metadatas-not-working)

**Comment by cadenkriese** [comment]
Hello, sorry for the inconvenience but Minecraft does not differentiate potions via item data anymore. Therefore Thirst can't tell the difference between a regular water bottle and a mundane one. I'll work on the change of format in an upcoming update but there is no reliable way for me to fix the bug, sorry.

**Comment by cadenkriese** [comment]
I made the formatting changes, you can download the update [here](https://www.spigotmc.org/resources/thirst.24610/update?update=164686). I added this to the list of known bugs found on the Spigot page. You can also wait for the auto updater to refresh and notify you it should refresh in no more than two hours.

Again, sorry for the inconvenience there's nothing I can really do.

**Comment by The-Mr-Mango** [comment]
http://minecraft.gamepedia.com/Data_values#Potions
isnt this how it works? correct me if im wrong
edit: and thank you a load for the change!

**Comment by cadenkriese** [comment]
Yes that is how Minecraft differentiates the potions within its own local code, however, from a plugin standpoint, those hex data values are not visible, for instance, if you try using /itemdb with Essentials on all the potions you will get the same result without any actual data values.

Edit: looking into that wiki page it does look like it's saying they're stored in the data values, however, it might be an inconsistency between Minecraft versions I currently support, and while testing with the 1.11 I found there to be no difference in data values, sorry. (If there is a version that thirst supports where potion data is stored in data values it will work with Thirst since I just directly compare the values between config and item that's being consumed.)

**Comment by The-Mr-Mango** [comment]
ugh how inconvenient! thanks anyways. hope this get fixed soon!!

**Comment by The-Mr-Mango** [comment]
Reply to edit: well it says it is an article for the latest version of MC. The values are a but cryptic, but they are there. I think they are there but if you say there is no way i believe you! Would be weird to not have any data values for different potions tho...

**Comment by cadenkriese** [comment]
Yeah, I'm not sure how that's working I just know that in 1.11.2 I can't detect any difference in data from the items.
